services:
  web:
    build: .
    command: ["uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=perfumancer.settings.prod
    depends_on:
      - redis

  nginx:
    image: nginx:1.25.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 1) Nginx-темплейты
      - ./config/nginx:/etc/nginx/templates:ro
      - .:/code
      # 2) «Живой» сертификат LE → путь, который ждёт конфиг
      - /etc/letsencrypt/live/perfumancer.ru/fullchain.pem:/code/perfumancer/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/perfumancer.ru/privkey.pem:/code/perfumancer/ssl/privkey.pem:ro

  celery:
    build: .
    command: celery -A perfumancer worker -l info
    restart: always
    volumes:
      - .:/code
    working_dir: /code/perfumancer
    environment:
      - DJANGO_SETTINGS_MODULE=perfumancer.settings.prod
    depends_on:
      - redis
      - web

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
