# Generated by Django 5.1.4 on 2024-12-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название поставщика"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Контактное лицо",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Адрес"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Веб-сайт"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Поставщика",
                "verbose_name_plural": "Поставщики",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("is_tester", models.BooleanField(default=False)),
                ("volume", models.DecimalField(decimal_places=1, max_digits=5)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="perfume.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_name", models.CharField(max_length=250)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_products",
                        to="perfume.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["raw_name"],
            },
        ),
        migrations.CreateModel(
            name="BrandAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="perfume.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "brand")},
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена товара",
                        max_digits=8,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Товар, к которому относится запись",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lists",
                        to="perfume.productbase",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Поставщик, поставляющий товар",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lists",
                        to="perfume.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прайс-лист",
                "verbose_name_plural": "Прайс-листы",
                "ordering": ["product"],
                "unique_together": {("product", "supplier")},
            },
        ),
    ]
