# Generated by Django 5.1.4 on 2024-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(max_length=3, unique=True, verbose_name="Валюта"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Курс"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс валюты",
                "verbose_name_plural": "Курсы валют",
            },
        ),
    ]
