# Generated by Django 5.1.4 on 2024-12-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0002_currencyrate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencyrate",
            options={"verbose_name": "Курс валюты", "verbose_name_plural": "Курс USD"},
        ),
    ]
