# Generated by Django 5.1.4 on 2025-01-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0005_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Покупатель", "verbose_name_plural": "Покупатели"},
        ),
        migrations.AlterModelOptions(
            name="orderproduct",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AddField(
            model_name="order",
            name="currency_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                editable=False,
                max_digits=10,
                verbose_name="Курс доллара на момент создания",
            ),
        ),
    ]
