# Generated by Django 5.1.4 on 2025-01-13 21:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0006_alter_customer_options_alter_orderproduct_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message='Номер телефона должен быть в формате: "+79991234567"',
                        regex="^\\+?7\\d{10}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=10,
                verbose_name="Количество",
            ),
        ),
    ]
