# Generated by Django 5.1.4 on 2025-05-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0007_alter_customer_phone_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Кабинет/Магазин",
                "verbose_name_plural": "Кабинеты/Магазины",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cabinet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="perfume.cabinet",
                verbose_name="Источник",
            ),
        ),
    ]
