# Generated by Django 5.1.4 on 2025-05-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0008_cabinet_orderitem_cabinet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="cabinet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="perfume.cabinet",
                verbose_name="Кабинет/Магазин",
            ),
        ),
    ]
