# Generated by Django 5.1.4 on 2025-06-14 10:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0009_alter_orderitem_cabinet"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название статуса"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код статуса"
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Порядок отображения")),
            ],
            options={
                "verbose_name": "Статус прихода",
                "verbose_name_plural": "Статусы приходов",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер накладной"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата накладной"
                    ),
                ),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="perfume.cabinet",
                        verbose_name="Кабинет/Магазин",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="perfume.order",
                        verbose_name="Связанный заказ",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="perfume.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="perfume.receiptstatus",
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приход",
                "verbose_name_plural": "Приходы",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование товара"
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Заказано"
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Фактически получено",
                    ),
                ),
                (
                    "purchase_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Фактическая цена закупки (USD)",
                    ),
                ),
                (
                    "purchase_price_rub",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Фактическая цена закупки (RUB)",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_items",
                        to="perfume.orderitem",
                        verbose_name="Позиция заказа",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="perfume.receipt",
                        verbose_name="Приход",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция прихода",
                "verbose_name_plural": "Позиции прихода",
                "unique_together": {("receipt", "order_item")},
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                apps.get_model("perfume", "ReceiptStatus").objects.get_or_create(
                    code=code, defaults={"name": name, "order": order}
                )
                for name, code, order in [
                    ("Черновик", "draft", 1),
                    ("Проведен", "completed", 2),
                    ("Отказ", "cancelled", 3),
                ]
            ],
            reverse_code=lambda apps, schema_editor: apps.get_model(
                "perfume", "ReceiptStatus"
            )
            .objects.filter(code__in=["draft", "completed", "cancelled"])
            .delete(),
        ),
    ]
