# Generated by Django 5.1.4 on 2025-06-14 21:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0010_receiptstatus_receipt_receiptitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="receiptitem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="perfume.order",
                verbose_name="Связанный заказ",
            ),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_items",
                to="perfume.orderitem",
                verbose_name="Позиция заказа",
            ),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="quantity_ordered",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Заказано",
            ),
        ),
    ]
