# Generated by Django 5.1.4 on 2025-06-14 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "perfume",
            "0011_alter_receiptitem_unique_together_alter_receipt_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptitem",
            name="quantity_ordered",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Заказано",
            ),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="quantity_received",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Фактически получено",
            ),
        ),
    ]
