# Generated by Django 5.1.4 on 2025-06-19 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0012_alter_receiptitem_quantity_ordered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="invoice_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите скан или фото накладной (PDF, JPG, PNG и др.)",
                null=True,
                upload_to="receipts/invoices/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "tiff",
                        ]
                    )
                ],
                verbose_name="Файл накладной",
            ),
        ),
    ]
