# Generated by Django 5.1.4 on 2025-07-07 20:36

import django.core.validators
import perfume.models.receipt
import perfume.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0014_update_receipt_invoice_file_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="heic_conversion_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает конвертации"),
                    ("processing", "Конвертируется"),
                    ("completed", "Завершено"),
                    ("failed", "Ошибка"),
                    ("not_needed", "Не требуется"),
                ],
                default="not_needed",
                help_text="Статус конвертации HEIC файлов в фоновом режиме",
                max_length=20,
                verbose_name="Статус конвертации HEIC",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="invoice_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите скан или фото накладной (PDF, JPG, PNG, HEIC и др.). HEIC файлы будут автоматически конвертированы в JPEG в фоновом режиме.",
                null=True,
                storage=perfume.storages.PrivateSelectelS3Storage(),
                upload_to=perfume.models.receipt.process_invoice_file_upload,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "tiff",
                            "heic",
                            "heif",
                        ]
                    )
                ],
                verbose_name="Файл накладной",
            ),
        ),
    ]
