# Generated by Django 5.1.4 on 2025-07-25 20:56

import django.core.validators
import perfume.models.receipt
import perfume.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfume", "0015_add_heic_conversion_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="heic_conversion_status",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="invoice_number",
        ),
        migrations.AlterField(
            model_name="receipt",
            name="invoice_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите скан или фото накладной (PDF, JPG, PNG, HEIC и др.). HEIC файлы автоматически конвертируются в JPEG. Файл сохраняется в защищенном хранилище.",
                null=True,
                storage=perfume.storages.PrivateSelectelS3Storage(),
                upload_to=perfume.models.receipt.process_invoice_file_upload,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "tiff",
                            "heic",
                            "heif",
                        ]
                    )
                ],
                verbose_name="Файл накладной",
            ),
        ),
    ]
